Feature/mycounter
mikhailalborisov/mycounter pull request #1
Opened 2022-10-06 14:52 UTC by mikhailalborisov

2022-10-06 15:07 UTC, AllStar6581 requested changes
.

2022-10-06 15:13 UTC, AllStar6581 commented
Нужно пройтись black по всему проекту

2022-10-07 17:33 UTC, AllStar6581 commented on mycounter/settings.py
> +    # "django.middleware.csrf.CsrfViewMiddleware",
Закомментированный код

2022-10-07 17:33 UTC, AllStar6581 commented on counterapp/views.py
> +        return JsonResponse({"count": "400"})
Может имелся в виду status_code 400?

2022-10-07 17:33 UTC, AllStar6581 commented on counterapp/tests.py
> +from django.test import TestCase
Лишний файл

2022-10-07 17:33 UTC, AllStar6581 commented on counterapp/models.py
> +from django.db import models
Лишний файл

2022-10-07 17:33 UTC, AllStar6581 commented on counterapp/admin.py
> +from django.contrib import admin
Лишний файл

2022-10-07 17:33 UTC, AllStar6581 commented on counterapp/views.py
> +# Create your views her
Забыл удалить комментарий

2022-10-07 17:33 UTC, AllStar6581 commented on counterapp/views.py
> +        return JsonResponse({"count": "400"})
Почему 400 это тело ответа а не status_code?

2022-10-29 19:31 UTC, mikhailalborisov commented on mycounter/settings.py
> +    # "django.middleware.csrf.CsrfViewMiddleware",
восстановил

2022-10-29 19:31 UTC, mikhailalborisov commented on counterapp/views.py
> +        return JsonResponse({"count": "400"})
поправил

2022-10-29 19:32 UTC, mikhailalborisov commented on counterapp/tests.py
> +from django.test import TestCase
написал тесты. файл не лишний

2022-10-29 19:32 UTC, mikhailalborisov commented on counterapp/models.py
> +from django.db import models
удалил

2022-10-29 19:33 UTC, mikhailalborisov commented on counterapp/admin.py
> +from django.contrib import admin
удалил

2022-10-29 19:33 UTC, mikhailalborisov commented on counterapp/views.py
> +# Create your views her
удалил

2022-10-29 19:34 UTC, mikhailalborisov commented on counterapp/views.py
> +        return JsonResponse({"count": "400"})
поправил

2022-11-22 10:43 UTC, merged